services:
  aio-web:
    build: .
    container_name: aio-toolkit
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./css:/usr/share/nginx/html/css
      - ./js:/usr/share/nginx/html/js
      - ./assets:/usr/share/nginx/html/assets
      - ./repo:/usr/share/nginx/html/repo
      - ./speedtest:/usr/share/nginx/html/speedtest
    restart: unless-stopped
